# Generated by Django 4.2 on 2026-03-19 00:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('url', models.TextField()),
                ('platform', models.CharField(default='instagram', max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('payload', 'Payload Ready'), ('failed', 'Failed'), ('cached', 'Cached')], default='queued', max_length=16)),
                ('source', models.CharField(default='live', max_length=16)),
                ('storage_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
